# Generated by Django 4.2 on 2023-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.CharField(max_length=100, verbose_name='نام url')),
                ('url_address', models.CharField(max_length=200, verbose_name='آدرس url')),
            ],
        ),
    ]
