# Generated by Django 4.2 on 2023-04-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksmodel',
            options={'verbose_name': 'لینک', 'verbose_name_plural': 'لینک ها'},
        ),
    ]
