# Generated by Django 4.2 on 2023-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0002_alter_linksmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='دسترسی عموم'),
        ),
    ]
