# Generated by Django 4.2 on 2023-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0003_linksmodel_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='برجسته شود/نشود'),
        ),
    ]
