# Generated by Django 4.0.6 on 2023-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0005_linksmodel_is_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='modal_target_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدال'),
        ),
    ]
