# Generated by Django 4.0.6 on 2023-04-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0006_linksmodel_modal_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksmodel',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود/نشود'),
        ),
    ]
