# Generated by Django 4.0.6 on 2023-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_module', '0007_linksmodel_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='نمایش داده شود/نشود'),
        ),
    ]
