# Generated by Django 4.2 on 2023-04-27 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200, verbose_name='نام تیم')),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captian', to=settings.AUTH_USER_MODEL, verbose_name='کاپیتان')),
                ('teamMate1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی اول')),
                ('teamMate2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی دوم')),
            ],
        ),
    ]
