# Generated by Django 4.2 on 2023-04-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsmodel',
            name='teamMate1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی اول'),
        ),
        migrations.AlterField(
            model_name='teamsmodel',
            name='teamMate2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی دوم'),
        ),
    ]
