# Generated by Django 4.2 on 2023-04-27 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_module', '0003_alter_teamsmodel_teammate1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsmodel',
            name='teamMate1',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی اول'),
        ),
        migrations.AlterField(
            model_name='teamsmodel',
            name='teamMate2',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondTeamMate', to=settings.AUTH_USER_MODEL, verbose_name='هم تیمی دوم'),
        ),
        migrations.CreateModel(
            name='inviteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False, verbose_name='قبول کردن/نکردن')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
        ),
    ]
