# Generated by Django 4.2 on 2023-04-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_module', '0005_invitemodel_invite_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitemodel',
            name='invite_id',
        ),
    ]
