# Generated by Django 4.2 on 2023-04-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_module', '0006_remove_invitemodel_invite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemodel',
            name='invite_id',
            field=models.CharField(default=None, max_length=100, verbose_name='شناسه دعوت'),
        ),
    ]
