# Generated by Django 4.0.6 on 2023-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_module', '0008_alter_invitemodel_invite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemodel',
            name='is_reject',
            field=models.BooleanField(default=False, verbose_name='رد کردن/نکردن'),
        ),
    ]
