# Generated by Django 4.2 on 2023-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_capitan',
            field=models.BooleanField(default=False, verbose_name='شرکت به عنوان کاپیتان'),
        ),
    ]
