# Generated by Django 4.2 on 2023-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_is_capitan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_team',
            field=models.BooleanField(default=False, verbose_name='تیم دارد/ندارد'),
        ),
    ]
